### ISSUE TITLE
Deprecated: Optional parameter $prefix declared before required parameter $identifier is implicitly treated as a required parameter

### ISSUE THREAD

**Issue by jsunier** [conlect/image-iiif#14]
Hi,

I get the following warning when calling the [`ImageIIIF::info` method](https://github.com/conlect/image-iiif/blob/2e34a929ea7ca7b62686d6fcb51755f019d1f55b/src/ImageIIIF.php#L83) even providing the two arguments (ex. `$file->info('iiif', 'test.jpg')`).

```
Deprecated: Optional parameter $prefix declared before required parameter $identifier is implicitly treated as a required parameter in /app/vendor/conlect/image-iiif/src/ImageIIIF.php on line 85
```

An easy fix would be to do something like this for the method signature :
```php
public function info(?string $prefix, string $identifier)
{
	$prefix ??= 'iiif';

	// ...
}
```

If you want i can make you a PR about that :wink:

**Comment by jeremytubbs** [comment]
Thanks for the info, I have decided to make `$prefix` required on release 1.1.0.
